resources:
  repositories:
  - repository: NSE_Report # The name used to reference this repository in the checkout step
    type: git
    name: Luckyy1998/NSE_Report
    
  - repository: Top_Gainers-Losers
    type: git
    name: Luckyy1998/Top_Gainers-Losers
  
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
- checkout: NSE_Report
- checkout: Top_Gainers-Losers

- script: dir $(Build.SourcesDirectory)
