resources:
  repositories:
  - repository: NSE_Report # The name used to reference this repository in the checkout step
    type: git
    name: Ansible-Test/NSE_Report.git
    
  - repository: Top_Gainer-Losers
    type: git
    name: Ansible-Test/Top_Gainer-Losers.git
  
trigger:
- master

pool:  
  name: local 

parameters:
- name: playbook
  displayName: 'Select the Playbook name you want to run:'
  type: string
  default: 'select'
  values:
    - 'NSE_Report/top_gainers_losers.py'
    - 'Top_Gainer-Losers/top_gainers_losers.py'

steps:
- checkout: self
- script: |
    echo "Files in self repository:"
    dir /s "$(Build.SourcesDirectory)"
  displayName: 'List files in self repository'
  
- task: Run Python file
    displayName: Run python
    condition: |
      or(
       eq('${{ parameters.playbook }}', 'NSE_Report/top_gainers_losers.py),
       eq('${{ parameters.playbook }}', 'Top_Gainer-Losers/top_gainers_losers.py')
      )
    inputs:
      inlineScript: python3 ${{parameters.playbook}}
  
  
- checkout: Top_Gainer-Losers
- script: |
    echo "Files in Top_Gainer-Losers repository:"
    dir /s "$(Build.SourcesDirectory)\Top_Gainer-Losers"
  displayName: 'List files in Top_Gainer-Losers repository'

- script: dir $(Build.SourcesDirectory)
