resources:
  repositories:
  - repository: NSE_Report # The name used to reference this repository in the checkout step
    type: git
    name: Ansible-Test/NSE_Report.git
    
  - repository: Top_Gainers-Losers
    type: git
    name: Ansible-Test/Top_Gainer-Losers.git
  
trigger:
- master

pool:  
  name: local 

steps:
- checkout: self
- checkout: NSE_Report
- checkout: Top_Gainers-Losers

- script: dir $(Build.SourcesDirectory)
