resources:
  repositories:
  - repository: NSE_Report # The name used to reference this repository in the checkout step
    type: git
    name: Ansible-Test/NSE_Report.git
    
  - repository: Top_Gainer-Losers
    type: git
    name: Ansible-Test/Top_Gainer-Losers.git
  
trigger:
- master

pool:  
  name: local 

parameters:
- name: playbook
  displayName: 'Select the Playbook name you want to run:'
  type: string
  default: 'select'
  values:
    - 'NSE_Report/top_gainers_losers.py'
    - 'Top_Gainer-Losers/top_gainers_losers.py'

jobs:
- job: ansible_ping
  displayName: Execute Ansible playbooks
  steps:
    - ${{ if eq(parameters.playbook, 'NSE_Report/top_gainers_losers.py') }}:
      - checkout: NSE_Report
      - script: echo Running ${{ parameters.playbook }} from $(Build.SourceBranch)
        displayName: 'Display running information'

    - ${{ if eq(parameters.playbook, 'Top_Gainer_Losers/top_gainers_losers.py') }}:
      - checkout: Top_Gainer_Losers
      - script: echo Running ${{ parameters.playbook }} from $(Build.SourceBranch)
        displayName: 'Display running information'

    - task: AzureCLI@2
      displayName: Run python
      inputs:
        scriptPath: ${{ parameters.playbook }}
