resources:
  repositories:
  - repository: NSE_Report # The name used to reference this repository in the checkout step
    type: git
    name: Ansible-Test/NSE_Report.git
    
  - repository: Top_Gainer-Losers
    type: git
    name: Ansible-Test/Top_Gainer-Losers.git
  
trigger:
- master

pool:  
  name: local 

steps:
- checkout: self
- script: |
    echo "Files in self repository:"
    dir /s $(Build.SourcesDirectory)
  displayName: 'List files in self repository'
  
- checkout: NSE_Report
- script: |
    echo "Files in NSE_Report repository:"
    dir /s $(Build.SourcesDirectory)/NSE_Report
  displayName: 'List files in NSE_Report repository'
  
- checkout: Top_Gainer-Losers
- script: |
    echo "Files in Top_Gainer-Losers repository:"
    dir /s $(Build.SourcesDirectory)/Top_Gainer-Losers
  displayName: 'List files in Top_Gainer-Losers repository'

- script: dir $(Build.SourcesDirectory)
